name: Build and Release APK

on:
  push:
    tags:
      - 'v*' # Triggers workflow when you push a tag like 'v1.0.4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install SQLite3
        run: sudo apt-get install -y sqlite3

      - name: Generate Database
        run: sqlite3 android/app/src/main/assets/thirukural.db < android/app/src/main/assets/thirukural.sql

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Release APK
        working-directory: ./android
        run: ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} Thirukkural-Widget-${{ github.ref_name }}.apk

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: Thirukkural-Widget-${{ github.ref_name }}.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
