name: Build and Release APK

on:
  push:
    tags:
      - 'v*' # Triggers workflow when you push a tag like 'v1.0.4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install SQLite3
        run: sudo apt-get install -y sqlite3

      - name: Generate Database
        run: sqlite3 android/app/src/main/assets/thirukural.db < android/app/src/main/assets/thirukural.sql

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Regenerate Gradle Wrapper JAR
        working-directory: ./android
        run: gradle wrapper --gradle-version 8.7

      - name: Build Release APK
        working-directory: ./android
        run: ./gradlew assembleRelease

      - name: Sign APK manually
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_FILE }}
          KEY_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          # Decode keystore
          echo "$KEYSTORE_BASE64" | base64 --decode > release.keystore
          
          # Find the latest build tools directory automatically
          export BUILD_TOOLS=$(ls -d /usr/local/lib/android/sdk/build-tools/* | tail -1)
          
          # Zipalign the APK
          $BUILD_TOOLS/zipalign -v -p 4 android/app/build/outputs/apk/release/app-release-unsigned.apk app-release-aligned.apk
          
          # Sign the APK
          $BUILD_TOOLS/apksigner sign --ks release.keystore --ks-key-alias "$KEY_ALIAS" --ks-pass pass:"$KEYSTORE_PASSWORD" --key-pass pass:"$KEY_PASSWORD" --out Thirukkural-Widget-${{ github.ref_name }}.apk app-release-aligned.apk
          
          # Clean up
          rm release.keystore app-release-aligned.apk

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: Thirukkural-Widget-${{ github.ref_name }}.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
